<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>PHP: Исключения - Manual </title>

 <link rel="icon" type="image/svg+xml" sizes="any" href="../../favicon.svg%3Fv=2">
 <link rel="icon" type="image/png" sizes="196x196" href="../../favicon-196x196.png%3Fv=2">
 <link rel="icon" type="image/png" sizes="32x32" href="../../favicon-32x32.png%3Fv=2">
 <link rel="icon" type="image/png" sizes="16x16" href="../../favicon-16x16.png%3Fv=2">
 <link rel="shortcut icon" href="../../favicon.ico%3Fv=2">

 <link rel="search" type="application/opensearchdescription+xml" href="http://php.net/phpnetimprovedsearch.src" title="Add PHP.net search">
 <link rel="alternate" type="application/atom+xml" href="https://www.php.net/releases/feed.php" title="PHP Release feed">
 <link rel="alternate" type="application/atom+xml" href="https://www.php.net/feed.atom" title="PHP: Hypertext Preprocessor">

 <link rel="canonical" href="language.exceptions.php.html">
 <link rel="shorturl" href="https://www.php.net/exceptions">
 <link rel="alternate" href="https://www.php.net/exceptions" hreflang="x-default">

 <link rel="contents" href="index.php.html">
 <link rel="index" href="langref.php.html">
 <link rel="prev" href="language.errors.php7.php.html">
 <link rel="next" href="language.exceptions.extending.php.html">

 <link rel="alternate" href="https://www.php.net/manual/en/language.exceptions.php" hreflang="en">
 <link rel="alternate" href="https://www.php.net/manual/de/language.exceptions.php" hreflang="de">
 <link rel="alternate" href="https://www.php.net/manual/es/language.exceptions.php" hreflang="es">
 <link rel="alternate" href="https://www.php.net/manual/fr/language.exceptions.php" hreflang="fr">
 <link rel="alternate" href="https://www.php.net/manual/it/language.exceptions.php" hreflang="it">
 <link rel="alternate" href="https://www.php.net/manual/ja/language.exceptions.php" hreflang="ja">
 <link rel="alternate" href="https://www.php.net/manual/pt_BR/language.exceptions.php" hreflang="pt_BR">
 <link rel="alternate" href="language.exceptions.php.html" hreflang="ru">
 <link rel="alternate" href="https://www.php.net/manual/tr/language.exceptions.php" hreflang="tr">
 <link rel="alternate" href="https://www.php.net/manual/zh/language.exceptions.php" hreflang="zh">

<link rel="stylesheet" type="text/css" href="../../cached.php%3Ft=1689765002&amp;f=%252Ffonts%252FFira%252Ffira.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cached.php%3Ft=1700771401&amp;f=%252Ffonts%252FFont-Awesome%252Fcss%252Ffontello.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cached.php%3Ft=1705413607&amp;f=%252Fstyles%252Ftheme-base.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cached.php%3Ft=1701958202&amp;f=%252Fstyles%252Ftheme-medium.css" media="screen">

 <base href="">


</head>
<body class="docs ">

<nav id="head-nav" class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <a href="https://www.php.net/" class="brand"><img src="../../images/logos/php-logo.svg" width="48" height="24" alt="php"></a>
    <div id="mainmenu-toggle-overlay"></div>
    <input type="checkbox" id="mainmenu-toggle">
    <ul class="nav">
      <li class=""><a href="https://www.php.net/downloads">Downloads</a></li>
      <li class="active"><a href="https://www.php.net/docs.php">Documentation</a></li>
      <li class=""><a href="https://www.php.net/get-involved" >Get Involved</a></li>
      <li class=""><a href="https://www.php.net/support">Help</a></li>
      <li class="">
        <a href="https://www.php.net/releases/8.3/index.php">
          <img src="../../images/php8/logo_php8_3.svg" alt="php8.3" height="22" width="60">
        </a>
      </li>
    </ul>
    <form class="navbar-search" id="topsearch" action="https://www.php.net/search.php">
      <input type="hidden" name="show" value="quickref">
      <input type="search" name="pattern" class="search-query" placeholder="Search" accesskey="s">
    </form>
  </div>
  <div id="flash-message"></div>
</nav>
<div class="headsup"><a href='https://www.php.net/conferences/index.php#2024-02-13-1'>Dutch PHP Conference 2024</a></div>
<nav id="trick"><div><dl>
<dt><a href='https://www.php.net/manual/en/getting-started.php'>Getting Started</a></dt>
	<dd><a href='https://www.php.net/manual/en/introduction.php'>Introduction</a></dd>
	<dd><a href='https://www.php.net/manual/en/tutorial.php'>A simple tutorial</a></dd>
<dt><a href='https://www.php.net/manual/en/langref.php'>Language Reference</a></dt>
	<dd><a href='https://www.php.net/manual/en/language.basic-syntax.php'>Basic syntax</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.types.php'>Types</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.variables.php'>Variables</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.constants.php'>Constants</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.expressions.php'>Expressions</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.operators.php'>Operators</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.control-structures.php'>Control Structures</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.functions.php'>Functions</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.oop5.php'>Classes and Objects</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.namespaces.php'>Namespaces</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.enumerations.php'>Enumerations</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.errors.php'>Errors</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.exceptions.php'>Exceptions</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.fibers.php'>Fibers</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.generators.php'>Generators</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.attributes.php'>Attributes</a></dd>
	<dd><a href='https://www.php.net/manual/en/language.references.php'>References Explained</a></dd>
	<dd><a href='https://www.php.net/manual/en/reserved.variables.php'>Predefined Variables</a></dd>
	<dd><a href='https://www.php.net/manual/en/reserved.exceptions.php'>Predefined Exceptions</a></dd>
	<dd><a href='https://www.php.net/manual/en/reserved.interfaces.php'>Predefined Interfaces and Classes</a></dd>
	<dd><a href='https://www.php.net/manual/en/reserved.attributes.php'>Predefined Attributes</a></dd>
	<dd><a href='https://www.php.net/manual/en/context.php'>Context options and parameters</a></dd>
	<dd><a href='https://www.php.net/manual/en/wrappers.php'>Supported Protocols and Wrappers</a></dd>
</dl>
<dl>
<dt><a href='https://www.php.net/manual/en/security.php'>Security</a></dt>
	<dd><a href='https://www.php.net/manual/en/security.intro.php'>Introduction</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.general.php'>General considerations</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.cgi-bin.php'>Installed as CGI binary</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.apache.php'>Installed as an Apache module</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.sessions.php'>Session Security</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.filesystem.php'>Filesystem Security</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.database.php'>Database Security</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.errors.php'>Error Reporting</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.variables.php'>User Submitted Data</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.hiding.php'>Hiding PHP</a></dd>
	<dd><a href='https://www.php.net/manual/en/security.current.php'>Keeping Current</a></dd>
<dt><a href='https://www.php.net/manual/en/features.php'>Features</a></dt>
	<dd><a href='https://www.php.net/manual/en/features.http-auth.php'>HTTP authentication with PHP</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.cookies.php'>Cookies</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.sessions.php'>Sessions</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.xforms.php'>Dealing with XForms</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.file-upload.php'>Handling file uploads</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.remote-files.php'>Using remote files</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.connection-handling.php'>Connection handling</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.persistent-connections.php'>Persistent Database Connections</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.commandline.php'>Command line usage</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.gc.php'>Garbage Collection</a></dd>
	<dd><a href='https://www.php.net/manual/en/features.dtrace.php'>DTrace Dynamic Tracing</a></dd>
</dl>
<dl>
<dt><a href='https://www.php.net/manual/en/funcref.php'>Function Reference</a></dt>
	<dd><a href='https://www.php.net/manual/en/refs.basic.php.php'>Affecting PHP's Behaviour</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.utilspec.audio.php'>Audio Formats Manipulation</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.remote.auth.php'>Authentication Services</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.utilspec.cmdline.php'>Command Line Specific Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.compression.php'>Compression and Archive Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.crypto.php'>Cryptography Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.database.php'>Database Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.calendar.php'>Date and Time Related Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.fileprocess.file.php'>File System Related Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.international.php'>Human Language and Character Encoding Support</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.utilspec.image.php'>Image Processing and Generation</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.remote.mail.php'>Mail Related Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.math.php'>Mathematical Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.utilspec.nontext.php'>Non-Text MIME Output</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.fileprocess.process.php'>Process Control Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.basic.other.php'>Other Basic Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.remote.other.php'>Other Services</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.search.php'>Search Engine Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.utilspec.server.php'>Server Specific Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.basic.session.php'>Session Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.basic.text.php'>Text Processing</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.basic.vartype.php'>Variable and Type Related Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.webservice.php'>Web Services</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.utilspec.windows.php'>Windows Only Extensions</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.xml.php'>XML Manipulation</a></dd>
	<dd><a href='https://www.php.net/manual/en/refs.ui.php'>GUI Extensions</a></dd>
</dl>
<dl>
<dt>Keyboard Shortcuts</dt><dt>?</dt>
<dd>This help</dd>
<dt>j</dt>
<dd>Next menu item</dd>
<dt>k</dt>
<dd>Previous menu item</dd>
<dt>g p</dt>
<dd>Previous man page</dd>
<dt>g n</dt>
<dd>Next man page</dd>
<dt>G</dt>
<dd>Scroll to bottom</dd>
<dt>g g</dt>
<dd>Scroll to top</dd>
<dt>g h</dt>
<dd>Goto homepage</dd>
<dt>g s</dt>
<dd>Goto search<br>(current page)</dd>
<dt>/</dt>
<dd>Focus search box</dd>
</dl></div></nav>
<div id="goto">
    <div class="search">
         <div class="text"></div>
         <div class="results"><ul></ul></div>
   </div>
</div>

  <div id="breadcrumbs" class="clearfix">
    <div id="breadcrumbs-inner">
          <div class="next">
        <a href="language.exceptions.extending.php.html">
          Наследование исключений &raquo;
        </a>
      </div>
              <div class="prev">
        <a href="language.errors.php7.php.html">
          &laquo; Ошибки в PHP 7        </a>
      </div>
          <ul>
            <li><a href='index.php.html'>Руководство по PHP</a></li>      <li><a href='langref.php.html'>Справочник языка</a></li>      </ul>
    </div>
  </div>




<div id="layout" class="clearfix">
  <section id="layout-content">
  <div class="page-tools">
    <div class="change-language">
      <form action="https://www.php.net/manual/change.php" method="get" id="changelang" name="changelang">
        <fieldset>
          <label for="changelang-langs">Change language:</label>
          <select onchange="document.changelang.submit()" name="page" id="changelang-langs">
            <option value='en/language.exceptions.php'>English</option>
            <option value='de/language.exceptions.php'>German</option>
            <option value='es/language.exceptions.php'>Spanish</option>
            <option value='fr/language.exceptions.php'>French</option>
            <option value='it/language.exceptions.php'>Italian</option>
            <option value='ja/language.exceptions.php'>Japanese</option>
            <option value='pt_BR/language.exceptions.php'>Brazilian Portuguese</option>
            <option value='ru/language.exceptions.php' selected="selected">Russian</option>
            <option value='tr/language.exceptions.php'>Turkish</option>
            <option value='zh/language.exceptions.php'>Chinese (Simplified)</option>
            <option value='help-translate.php'>Other</option>
          </select>
        </fieldset>
      </form>
    </div>
    <div class="edit-bug">
      <a href="https://github.com/php/doc-ru/blob/master/language/exceptions.xml">Submit a Pull Request</a>
      <a href="https://github.com/php/doc-ru/issues/new?body=From%20manual%20page:%20https:%2F%2Fphp.net%2Flanguage.exceptions%0A%0A---">Report a Bug</a>
    </div>
  </div><div id="language.exceptions" class="chapter">
 <h1>Исключения</h1>
<h2>Содержание</h2><ul class="chunklist chunklist_chapter"><li><a href="language.exceptions.extending.php.html">Наследование исключений</a></li></ul>

 <p class="para">
  В PHP реализована модель исключений, аналогичная тем, что используются в других языках программирования.
  Исключение в PHP может быть выброшено (<a href="language.exceptions.php.html" class="link"><code class="literal">throw</code></a>) и поймано (<a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>).
  Код может быть заключён в блок <a href="language.exceptions.php.html" class="link"><code class="literal">try</code></a>, чтобы облегчить обработку потенциальных исключений.
  У каждого блока <a href="language.exceptions.php.html" class="link"><code class="literal">try</code></a> должен быть как минимум один соответствующий блок <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a> или <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a>.
 </p>
 <p class="para">
  Если выброшено исключение, а в текущей области видимости функции нет блока <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>,
  исключение будет &quot;подниматься&quot; по стеку вызовов к вызывающей функции, пока не найдёт подходящий блок <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>.
  Все блоки <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a>, которые встретятся на этом пути, будут выполнены.
  Если стек вызовов разворачивается до глобальной области видимости, не встречая подходящего блока <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>,
  программа завершается с неисправимой ошибкой, если не был установлен глобальный обработчик исключений.
 </p>
 <p class="para">
  Выброшенный объект должен наследовать (<a href="language.operators.type.php.html" class="link"><code class="literal">instanceof</code></a>) интерфейс <span class="interfacename"><a href="class.throwable.php.html" class="interfacename">Throwable</a></span>.
  Попытка выбросить объект, который таковым не является, приведёт к неисправимой ошибке PHP.
 </p>
 <p class="para">
  Начиная с PHP 8.0.0, ключевое слово <a href="language.exceptions.php.html" class="link"><code class="literal">throw</code></a> является выражением и может быть использовано
  в любом контексте выражения. В предыдущих версиях оно было утверждением
  и должно было располагаться в отдельной строке.
 </p>

 <div id="language.exceptions.catch" class="sect1">
  <h2 class="title"><code class="literal">catch</code></h2>
  <p class="para">
   Блок <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a> определяет, как реагировать на выброшенное исключение.
   Блок <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a> определяет один или несколько типов исключений или ошибок, которые он может обработать,
   и, по желанию, переменную, которой можно присвоить исключение
   (указание переменной было обязательно до версии PHP 8.0.0).
   Первый блок <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>, с которым столкнётся выброшенное исключение или ошибка
   и соответствует типу выброшенного объекта, обработает объект.
  </p>
  <p class="para">
   Несколько блоков <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a> могут быть использованы для перехвата различных классов исключений.
   Нормальное выполнение (когда исключение не выброшено в блоке <a href="language.exceptions.php.html" class="link"><code class="literal">try</code></a>)
   будет продолжаться после последнего блока <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>, определённого в последовательности.
   Исключения могут быть выброшены (<a href="language.exceptions.php.html" class="link"><code class="literal">throw</code></a>) (или повторно выброшены) внутри блока <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>.
   В противном случае выполнение будет продолжено после блока <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>, который был вызван.
  </p>
  <p class="para">
   При возникновении исключения, код, следующий за утверждением, не будет выполнен,
   а PHP попытается найти первый подходящий блок <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>.
   Если исключение не поймано, будет выдана неисправимая ошибка PHP
   с сообщением &quot;<code class="literal">Uncaught Exception ...</code>&quot;,
   если только обработчик не был определён с помощью функции <span class="function"><a href="function.set-exception-handler.php.html" class="function">set_exception_handler()</a></span>.
  </p>
  <p class="para">
   Начиная с версии PHP 7.1.0, в блоке <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a> можно указывать несколько исключений,
   используя символ <code class="literal">|</code>. Это полезно, когда разные исключения
   из разных иерархий классов обрабатываются одинаково.
  </p>
  <p class="para">
   Начиная с версии PHP 8.0.0, имя переменной для пойманного исключения является необязательным.
   Если оно не указано, блок <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a> будет выполнен,
   но не будет иметь доступа к выброшенному объекту.
  </p>
 </div>

 <div id="language.exceptions.finally" class="sect1">
  <h2 class="title"><code class="literal">finally</code></h2>
  <p class="para">
   Блок <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a> также может быть указан после или вместо блоков <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>.
   Код в блоке <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a> всегда будет выполняться после блоков <a href="language.exceptions.php.html" class="link"><code class="literal">try</code></a> и <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>,
   независимо от того, было ли выброшено исключение
   и до возобновления нормального выполнения.
  </p>
  <p class="para">
   Одно из заметных взаимодействий происходит между блоком <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a> и оператором <a href="function.return.php.html" class="link"><code class="literal">return</code></a>.
   Если оператор <a href="function.return.php.html" class="link"><code class="literal">return</code></a> встречается внутри блоков <a href="language.exceptions.php.html" class="link"><code class="literal">try</code></a> или <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>, блок <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a>
   всё равно будет выполнен. Более того, оператор <a href="function.return.php.html" class="link"><code class="literal">return</code></a> выполнится, когда встретится,
   но результат будет возвращён после выполнения блока <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a>.
   Кроме того, если блок <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a> также содержит оператор <a href="function.return.php.html" class="link"><code class="literal">return</code></a>,
   возвращается значение из блока <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a>.
  </p>
 </div>

 <div id="language.exceptions.exception-handler" class="sect1">
  <h2 class="title">Глобальный обработчик исключений</h2>
  <p class="para">
   Если исключению разрешено распространяться на глобальную область видимости,
   оно может быть перехвачено глобальным обработчиком исключений, если он установлен.
   Функция <span class="function"><a href="function.set-exception-handler.php.html" class="function">set_exception_handler()</a></span> может задать функцию,
   которая будет вызвана вместо блока <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>, если не будет вызван никакой другой блок.
   Эффект по сути такой же, как если бы вся программа была обёрнута в блок <a href="language.exceptions.php.html" class="link"><code class="literal">try</code></a>-<a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>
   с этой функцией в качестве <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a>.
  </p>
 </div>

 <div id="language.exceptions.notes" class="sect1">
  <h2 class="title">Примечания</h2>

  <blockquote class="note"><p><strong class="note">Замечание</strong>: 
   <p class="para">
    Внутренние функции PHP в основном используют <a href="errorfunc.configuration.php.html#ini.error-reporting" class="link">отчёт об ошибках</a>,
    только современные <a href="language.oop5.php.html" class="link">объектно-ориентированные</a> модули используют исключения.
    Однако ошибки можно легко перевести в исключения с помощью класса <a href="class.errorexception.php.html" class="link">ErrorException</a>.
    Однако эта техника работает только с исправляемыми ошибками.
   </p>
   <div class="example" id="example-991">
    <p><strong>Пример #1 Преобразование отчётов об ошибках в исключения</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function </span><span style="color: #0000BB">exceptions_error_handler</span><span style="color: #007700">(</span><span style="color: #0000BB">$severity</span><span style="color: #007700">, </span><span style="color: #0000BB">$message</span><span style="color: #007700">, </span><span style="color: #0000BB">$filename</span><span style="color: #007700">, </span><span style="color: #0000BB">$lineno</span><span style="color: #007700">) {<br />    throw new </span><span style="color: #0000BB">ErrorException</span><span style="color: #007700">(</span><span style="color: #0000BB">$message</span><span style="color: #007700">, </span><span style="color: #0000BB">0</span><span style="color: #007700">, </span><span style="color: #0000BB">$severity</span><span style="color: #007700">, </span><span style="color: #0000BB">$filename</span><span style="color: #007700">, </span><span style="color: #0000BB">$lineno</span><span style="color: #007700">);<br />}<br /><br /></span><span style="color: #0000BB">set_error_handler</span><span style="color: #007700">(</span><span style="color: #DD0000">'exceptions_error_handler'</span><span style="color: #007700">);<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
    </div>

   </div>
  </p></blockquote>
  <div class="tip"><strong class="tip">Подсказка</strong>
   <p class="para">
    Библиотека <a href="intro.spl.php.html" class="link">Стандартная библиотека PHP (SPL)</a>
    предоставляет большое количество <a href="spl.exceptions.php.html" class="link">встроенных исключений</a>.
   </p>
  </div>
 </div>

 <div id="language.exceptions.examples" class="sect1">
  <h2 class="title">Примеры</h2>

  <div class="example" id="sodium-crypto-generichash-final.example.basic">
   <p><strong>Пример #2 Выбрасывание исключения</strong></p>
   <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">) {<br />    if (!</span><span style="color: #0000BB">$x</span><span style="color: #007700">) {<br />        throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Деление на ноль.'</span><span style="color: #007700">);<br />    }<br />    return </span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try {<br />    echo </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">) . </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />    echo </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">) . </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />    echo </span><span style="color: #DD0000">'Выброшено исключение: '</span><span style="color: #007700">,  </span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(), </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">// Продолжение выполнения<br /></span><span style="color: #007700">echo </span><span style="color: #DD0000">"Привет, мир\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
   </div>

   
<div class="example-contents"><p>
 Результат выполнения приведённого примера:
</p></div>

   <div class="example-contents screen">
<div class="cdata"><pre>
0.2
Выброшено исключение: Деление на ноль.
Привет, мир
</pre></div>
   </div>
  </div>
  <div class="example" id="sodium-crypto-kx-keypair.example.basic">
   <p><strong>Пример #3 Обработка исключений с помощью блока <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a></strong></p>
   <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">) {<br />    if (!</span><span style="color: #0000BB">$x</span><span style="color: #007700">) {<br />        throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Деление на ноль.'</span><span style="color: #007700">);<br />    }<br />    return </span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try {<br />    echo </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">) . </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />    echo </span><span style="color: #DD0000">'Поймано исключение: '</span><span style="color: #007700">,  </span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(), </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} finally {<br />    echo </span><span style="color: #DD0000">"Первый блок finally.\n"</span><span style="color: #007700">;<br />}<br /><br />try {<br />    echo </span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">) . </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />    echo </span><span style="color: #DD0000">'Поймано исключение: '</span><span style="color: #007700">,  </span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(), </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />} finally {<br />    echo </span><span style="color: #DD0000">"Второй блок finally.\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">// Продолжение нормального выполнения<br /></span><span style="color: #007700">echo </span><span style="color: #DD0000">"Привет, мир\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
   </div>

   
<div class="example-contents"><p>
 Результат выполнения приведённого примера:
</p></div>

   <div class="example-contents screen">
<div class="cdata"><pre>
0.2
Первый блок finally.
Поймано исключение: Деление на ноль.
Второй блок finally.
Привет, мир
</pre></div>
   </div>
  </div>
  <div class="example" id="example-1000">
   <p><strong>Пример #4 Взаимодействие между блоками <a href="language.exceptions.php.html" class="link"><code class="literal">finally</code></a> и <a href="function.return.php.html" class="link"><code class="literal">return</code></a></strong></p>
   <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">function </span><span style="color: #0000BB">test</span><span style="color: #007700">() {<br />    try {<br />        throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo'</span><span style="color: #007700">);<br />    } catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />        return </span><span style="color: #DD0000">'catch'</span><span style="color: #007700">;<br />    } finally {<br />        return </span><span style="color: #DD0000">'finally'</span><span style="color: #007700">;<br />    }<br />}<br /><br />echo </span><span style="color: #0000BB">test</span><span style="color: #007700">();<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
   </div>

   
<div class="example-contents"><p>
 Результат выполнения приведённого примера:
</p></div>

   <div class="example-contents screen">
<div class="cdata"><pre>
finally
</pre></div>
   </div>
  </div>
  <div class="example" id="example-1003">
   <p><strong>Пример #5 Вложенные исключения</strong></p>
   <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class </span><span style="color: #0000BB">MyException </span><span style="color: #007700">extends </span><span style="color: #0000BB">Exception </span><span style="color: #007700">{ }<br /><br />class </span><span style="color: #0000BB">Test </span><span style="color: #007700">{<br />    public function </span><span style="color: #0000BB">testing</span><span style="color: #007700">() {<br />        try {<br />            try {<br />                throw new </span><span style="color: #0000BB">MyException</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo!'</span><span style="color: #007700">);<br />            } catch (</span><span style="color: #0000BB">MyException $e</span><span style="color: #007700">) {<br />                </span><span style="color: #FF8000">// повторный выброс исключения<br />                </span><span style="color: #007700">throw </span><span style="color: #0000BB">$e</span><span style="color: #007700">;<br />            }<br />        } catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />            </span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">());<br />        }<br />    }<br />}<br /><br /></span><span style="color: #0000BB">$foo </span><span style="color: #007700">= new </span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
   </div>

   
<div class="example-contents"><p>
 Результат выполнения приведённого примера:
</p></div>

   <div class="example-contents screen">
<div class="cdata"><pre>
string(4) &quot;foo!&quot;
</pre></div>
   </div>
  </div>
  <div class="example" id="example-1006">
   <p><strong>Пример #6 Обработка нескольких исключений в одном блоке catch</strong></p>
   <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class </span><span style="color: #0000BB">MyException </span><span style="color: #007700">extends </span><span style="color: #0000BB">Exception </span><span style="color: #007700">{ }<br /><br />class </span><span style="color: #0000BB">MyOtherException </span><span style="color: #007700">extends </span><span style="color: #0000BB">Exception </span><span style="color: #007700">{ }<br /><br />class </span><span style="color: #0000BB">Test </span><span style="color: #007700">{<br />    public function </span><span style="color: #0000BB">testing</span><span style="color: #007700">() {<br />        try {<br />            throw new </span><span style="color: #0000BB">MyException</span><span style="color: #007700">();<br />        } catch (</span><span style="color: #0000BB">MyException </span><span style="color: #007700">| </span><span style="color: #0000BB">MyOtherException $e</span><span style="color: #007700">) {<br />            </span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">get_class</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">));<br />        }<br />    }<br />}<br /><br /></span><span style="color: #0000BB">$foo </span><span style="color: #007700">= new </span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
   </div>

   
<div class="example-contents"><p>
 Результат выполнения приведённого примера:
</p></div>

   <div class="example-contents screen">
<div class="cdata"><pre>
string(11) &quot;MyException&quot;
</pre></div>
   </div>
  </div>
  <div class="example" id="example-1009">
   <p><strong>Пример #7 Пример блока <a href="language.exceptions.php.html" class="link"><code class="literal">catch</code></a> без указания переменной</strong></p>
   <div class="example-contents"><p>Допустимо начиная с PHP 8.0.0</p></div>
   <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class </span><span style="color: #0000BB">SpecificException </span><span style="color: #007700">extends </span><span style="color: #0000BB">Exception </span><span style="color: #007700">{}<br /><br />function </span><span style="color: #0000BB">test</span><span style="color: #007700">() {<br />    throw new </span><span style="color: #0000BB">SpecificException</span><span style="color: #007700">(</span><span style="color: #DD0000">'Ой!'</span><span style="color: #007700">);<br />}<br /><br />try {<br />    </span><span style="color: #0000BB">test</span><span style="color: #007700">();<br />} catch (</span><span style="color: #0000BB">SpecificException</span><span style="color: #007700">) {<br />    print </span><span style="color: #DD0000">"Было поймано исключение SpecificException, но нам безразлично, что у него внутри."</span><span style="color: #007700">;<br />}<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
   </div>

  </div>
  <div class="example" id="example-1012">
   <p><strong>Пример #8 Throw как выражение</strong></p>
   <div class="example-contents"><p>Допустимо начиная с PHP 8.0.0</p></div>
   <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000"><span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">function </span><span style="color: #0000BB">test</span><span style="color: #007700">() {<br />    </span><span style="color: #0000BB">do_something_risky</span><span style="color: #007700">() or throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Всё сломалось'</span><span style="color: #007700">);<br />}<br /><br />try {<br />    </span><span style="color: #0000BB">test</span><span style="color: #007700">();<br />} catch (</span><span style="color: #0000BB">Exception $e</span><span style="color: #007700">) {<br />    print </span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">();<br />}<br /></span><span style="color: #0000BB">?&gt;</span></span></code></div>
   </div>

  </div>
 </div>

 

</div>
<section id="usernotes">
 <div class="head">
  <span class="action"><a href="https://www.php.net/manual/add-note.php?sect=language.exceptions&amp;redirect=https://www.php.net/manual/ru/language.exceptions.php">＋<small>add a note</small></a></span>
  <h3 class="title">User Contributed Notes <span class="count">15 notes</span></h3>
 </div><div id="allnotes">
  <div class="note" id="91159">  <div class="votes">
    <div id="Vu91159">
    <a href="https://www.php.net/manual/vote-note.php?id=91159&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd91159">
    <a href="https://www.php.net/manual/vote-note.php?id=91159&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V91159" title="68% like this...">
    118
    </div>
  </div>
  <a href="language.exceptions.php.html#91159" class="name">
  <strong class="user"><em>ask at nilpo dot com</em></strong></a><a class="genanchor" href="language.exceptions.php.html#91159"> &para;</a><div class="date" title="2009-05-27 12:19"><strong>14 years ago</strong></div>
  <div class="text" id="Hcom91159">
<div class="phpcode"><code><span class="html">If you intend on creating a lot of custom exceptions, you may find this code useful.  I've created an interface and an abstract exception class that ensures that all parts of the built-in Exception class are preserved in child classes.  It also properly pushes all information back to the parent constructor ensuring that nothing is lost.  This allows you to quickly create new exceptions on the fly.  It also overrides the default __toString method with a more thorough one.<br /><br /><span class="default">&lt;?php<br /></span><span class="keyword">interface </span><span class="default">IException<br /></span><span class="keyword">{<br />    </span><span class="comment">/* Protected methods inherited from Exception class */<br />    </span><span class="keyword">public function </span><span class="default">getMessage</span><span class="keyword">();                 </span><span class="comment">// Exception message <br />    </span><span class="keyword">public function </span><span class="default">getCode</span><span class="keyword">();                    </span><span class="comment">// User-defined Exception code<br />    </span><span class="keyword">public function </span><span class="default">getFile</span><span class="keyword">();                    </span><span class="comment">// Source filename<br />    </span><span class="keyword">public function </span><span class="default">getLine</span><span class="keyword">();                    </span><span class="comment">// Source line<br />    </span><span class="keyword">public function </span><span class="default">getTrace</span><span class="keyword">();                   </span><span class="comment">// An array of the backtrace()<br />    </span><span class="keyword">public function </span><span class="default">getTraceAsString</span><span class="keyword">();           </span><span class="comment">// Formated string of trace<br />    <br />    /* Overrideable methods inherited from Exception class */<br />    </span><span class="keyword">public function </span><span class="default">__toString</span><span class="keyword">();                 </span><span class="comment">// formated string for display<br />    </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">);<br />}<br /><br />abstract class </span><span class="default">CustomException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">implements </span><span class="default">IException<br /></span><span class="keyword">{<br />    protected </span><span class="default">$message </span><span class="keyword">= </span><span class="string">'Unknown exception'</span><span class="keyword">;     </span><span class="comment">// Exception message<br />    </span><span class="keyword">private   </span><span class="default">$string</span><span class="keyword">;                            </span><span class="comment">// Unknown<br />    </span><span class="keyword">protected </span><span class="default">$code    </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">;                       </span><span class="comment">// User-defined exception code<br />    </span><span class="keyword">protected </span><span class="default">$file</span><span class="keyword">;                              </span><span class="comment">// Source filename of exception<br />    </span><span class="keyword">protected </span><span class="default">$line</span><span class="keyword">;                              </span><span class="comment">// Source line of exception<br />    </span><span class="keyword">private   </span><span class="default">$trace</span><span class="keyword">;                             </span><span class="comment">// Unknown<br /><br />    </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">)<br />    {<br />        if (!</span><span class="default">$message</span><span class="keyword">) {<br />            throw new </span><span class="default">$this</span><span class="keyword">(</span><span class="string">'Unknown '</span><span class="keyword">. </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">));<br />        }<br />        </span><span class="default">parent</span><span class="keyword">::</span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">);<br />    }<br />    <br />    public function </span><span class="default">__toString</span><span class="keyword">()<br />    {<br />        return </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">) . </span><span class="string">" '</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">message</span><span class="keyword">}</span><span class="string">' in </span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">file</span><span class="keyword">}</span><span class="string">(</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">line</span><span class="keyword">}</span><span class="string">)\n"<br />                                </span><span class="keyword">. </span><span class="string">"</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">()}</span><span class="string">"</span><span class="keyword">;<br />    }<br />}<br /></span><span class="default">?&gt;<br /></span><br />Now you can create new exceptions in one line:<br /><br /><span class="default">&lt;?php<br /></span><span class="keyword">class </span><span class="default">TestException </span><span class="keyword">extends </span><span class="default">CustomException </span><span class="keyword">{}<br /></span><span class="default">?&gt;<br /></span><br />Here's a test that shows that all information is properly preserved throughout the backtrace.<br /><br /><span class="default">&lt;?php<br /></span><span class="keyword">function </span><span class="default">exceptionTest</span><span class="keyword">()<br />{<br />    try {<br />        throw new </span><span class="default">TestException</span><span class="keyword">();<br />    }<br />    catch (</span><span class="default">TestException $e</span><span class="keyword">) {<br />        echo </span><span class="string">"Caught TestException ('</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">')\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n"</span><span class="keyword">;<br />    }<br />    catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />        echo </span><span class="string">"Caught Exception ('</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">')\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n"</span><span class="keyword">;<br />    }<br />}<br /><br />echo </span><span class="string">'&lt;pre&gt;' </span><span class="keyword">. </span><span class="default">exceptionTest</span><span class="keyword">() . </span><span class="string">'&lt;/pre&gt;'</span><span class="keyword">;<br /></span><span class="default">?&gt;<br /></span><br />Here's a sample output:<br /><br />Caught TestException ('Unknown TestException')<br />TestException 'Unknown TestException' in C:\xampp\htdocs\CustomException\CustomException.php(31)<br />#0 C:\xampp\htdocs\CustomException\ExceptionTest.php(19): CustomException-&gt;__construct()<br />#1 C:\xampp\htdocs\CustomException\ExceptionTest.php(43): exceptionTest()<br />#2 {main}</span></code></div>
  </div>
 </div>
  <div class="note" id="128869">  <div class="votes">
    <div id="Vu128869">
    <a href="https://www.php.net/manual/vote-note.php?id=128869&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd128869">
    <a href="https://www.php.net/manual/vote-note.php?id=128869&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V128869" title="100% like this...">
    6
    </div>
  </div>
  <a href="language.exceptions.php.html#128869" class="name">
  <strong class="user"><em>tianyiw at vip dot qq dot com</em></strong></a><a class="genanchor" href="language.exceptions.php.html#128869"> &para;</a><div class="date" title="2023-09-08 03:11"><strong>5 months ago</strong></div>
  <div class="text" id="Hcom128869">
<div class="phpcode"><code><span class="html">Easy to understand `finally`.<br /><span class="default">&lt;?php<br /></span><span class="keyword">try {<br />    try {<br />        echo </span><span class="string">"before\n"</span><span class="keyword">;<br />        </span><span class="default">1 </span><span class="keyword">/ </span><span class="default">0</span><span class="keyword">;<br />        echo </span><span class="string">"after\n"</span><span class="keyword">;<br />    } finally {<br />        echo </span><span class="string">"finally\n"</span><span class="keyword">;<br />    }<br />} catch (</span><span class="default">\Throwable</span><span class="keyword">) {<br />    echo </span><span class="string">"exception\n"</span><span class="keyword">;<br />}<br /></span><span class="default">?&gt;<br /></span># Print:<br />before<br />finally<br />exception</span></code></div>
  </div>
 </div>
  <div class="note" id="103819">  <div class="votes">
    <div id="Vu103819">
    <a href="https://www.php.net/manual/vote-note.php?id=103819&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd103819">
    <a href="https://www.php.net/manual/vote-note.php?id=103819&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V103819" title="62% like this...">
    81
    </div>
  </div>
  <a href="language.exceptions.php.html#103819" class="name">
  <strong class="user"><em>Johan</em></strong></a><a class="genanchor" href="language.exceptions.php.html#103819"> &para;</a><div class="date" title="2011-05-05 01:18"><strong>12 years ago</strong></div>
  <div class="text" id="Hcom103819">
<div class="phpcode"><code><span class="html">Custom error handling on entire pages can avoid half rendered pages for the users:<br /><br /><span class="default">&lt;?php<br />ob_start</span><span class="keyword">();<br />try {<br />    </span><span class="comment">/*contains all page logic <br />    and throws error if needed*/<br />    </span><span class="keyword">...<br />} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />  </span><span class="default">ob_end_clean</span><span class="keyword">();<br />  </span><span class="default">displayErrorPage</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br />}<br /></span><span class="default">?&gt;</span></span></code></div>
  </div>
 </div>
  <div class="note" id="86476">  <div class="votes">
    <div id="Vu86476">
    <a href="https://www.php.net/manual/vote-note.php?id=86476&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd86476">
    <a href="https://www.php.net/manual/vote-note.php?id=86476&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V86476" title="63% like this...">
    22
    </div>
  </div>
  <a href="language.exceptions.php.html#86476" class="name">
  <strong class="user"><em>Shot (Piotr Szotkowski)</em></strong></a><a class="genanchor" href="language.exceptions.php.html#86476"> &para;</a><div class="date" title="2008-10-21 12:13"><strong>15 years ago</strong></div>
  <div class="text" id="Hcom86476">
<div class="phpcode"><code><span class="html">‘Normal execution (when no exception is thrown within the try block, *or when a catch matching the thrown exception’s class is not present*) will continue after that last catch block defined in sequence.’<br /><br />‘If an exception is not caught, a PHP Fatal Error will be issued with an “Uncaught Exception …” message, unless a handler has been defined with set_exception_handler().’<br /><br />These two sentences seem a bit contradicting about what happens ‘when a catch matching the thrown exception’s class is not present’ (and the second sentence is actually correct).</span></code></div>
  </div>
 </div>
  <div class="note" id="121673">  <div class="votes">
    <div id="Vu121673">
    <a href="https://www.php.net/manual/vote-note.php?id=121673&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd121673">
    <a href="https://www.php.net/manual/vote-note.php?id=121673&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V121673" title="63% like this...">
    12
    </div>
  </div>
  <a href="language.exceptions.php.html#121673" class="name">
  <strong class="user"><em>daviddlowe dot flimm at gmail dot com</em></strong></a><a class="genanchor" href="language.exceptions.php.html#121673"> &para;</a><div class="date" title="2017-09-22 01:13"><strong>6 years ago</strong></div>
  <div class="text" id="Hcom121673">
<div class="phpcode"><code><span class="html">Starting in PHP 7, the classes Exception and Error both implement the Throwable interface. This means, if you want to catch both Error instances and Exception instances, you should catch Throwable objects, like this:<br /><br /><span class="default">&lt;?php<br /><br /></span><span class="keyword">try {<br />    throw new </span><span class="default">Error</span><span class="keyword">( </span><span class="string">"foobar" </span><span class="keyword">);<br />    </span><span class="comment">// or:<br />    // throw new Exception( "foobar" );<br /></span><span class="keyword">}<br />catch (</span><span class="default">Throwable $e</span><span class="keyword">) {<br />    </span><span class="default">var_export</span><span class="keyword">( </span><span class="default">$e </span><span class="keyword">);<br />}<br /><br /></span><span class="default">?&gt;</span></span></code></div>
  </div>
 </div>
  <div class="note" id="121228">  <div class="votes">
    <div id="Vu121228">
    <a href="https://www.php.net/manual/vote-note.php?id=121228&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd121228">
    <a href="https://www.php.net/manual/vote-note.php?id=121228&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V121228" title="63% like this...">
    12
    </div>
  </div>
  <a href="language.exceptions.php.html#121228" class="name">
  <strong class="user"><em>christof+php[AT]insypro.com</em></strong></a><a class="genanchor" href="language.exceptions.php.html#121228"> &para;</a><div class="date" title="2017-06-15 10:12"><strong>6 years ago</strong></div>
  <div class="text" id="Hcom121228">
<div class="phpcode"><code><span class="html">In case your E_WARNING type of errors aren't catchable with try/catch you can change them to another type of error like this:<br /><br /><span class="default">&lt;?php <br />    set_error_handler</span><span class="keyword">(function(</span><span class="default">$errno</span><span class="keyword">, </span><span class="default">$errstr</span><span class="keyword">, </span><span class="default">$errfile</span><span class="keyword">, </span><span class="default">$errline</span><span class="keyword">){<br />            if(</span><span class="default">$errno </span><span class="keyword">=== </span><span class="default">E_WARNING</span><span class="keyword">){<br />                </span><span class="comment">// make it more serious than a warning so it can be caught<br />                </span><span class="default">trigger_error</span><span class="keyword">(</span><span class="default">$errstr</span><span class="keyword">, </span><span class="default">E_ERROR</span><span class="keyword">);<br />                return </span><span class="default">true</span><span class="keyword">;<br />            } else {<br />                </span><span class="comment">// fallback to default php error handler<br />                </span><span class="keyword">return </span><span class="default">false</span><span class="keyword">;<br />            }<br />    });<br /><br />    try {<br />            </span><span class="comment">// code that might result in a E_WARNING<br />    </span><span class="keyword">} catch(</span><span class="default">Exception $e</span><span class="keyword">){<br />            </span><span class="comment">// code to handle the E_WARNING (it's actually changed to E_ERROR at this point)<br />    </span><span class="keyword">} finally {<br />            </span><span class="default">restore_error_handler</span><span class="keyword">();<br />    }<br /></span><span class="default">?&gt;</span></span></code></div>
  </div>
 </div>
  <div class="note" id="112507">  <div class="votes">
    <div id="Vu112507">
    <a href="https://www.php.net/manual/vote-note.php?id=112507&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd112507">
    <a href="https://www.php.net/manual/vote-note.php?id=112507&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V112507" title="57% like this...">
    21
    </div>
  </div>
  <a href="language.exceptions.php.html#112507" class="name">
  <strong class="user"><em>Edu</em></strong></a><a class="genanchor" href="language.exceptions.php.html#112507"> &para;</a><div class="date" title="2013-06-24 06:13"><strong>10 years ago</strong></div>
  <div class="text" id="Hcom112507">
<div class="phpcode"><code><span class="html">The "finally" block can change the exception that has been throw by the catch block.<br /><br /><span class="default">&lt;?php<br /></span><span class="keyword">try{<br />        try {<br />                throw new </span><span class="default">\Exception</span><span class="keyword">(</span><span class="string">"Hello"</span><span class="keyword">);<br />        } catch(</span><span class="default">\Exception $e</span><span class="keyword">) {<br />                echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" catch in\n"</span><span class="keyword">;<br />                throw </span><span class="default">$e</span><span class="keyword">;<br />        } finally {<br />                echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" finally \n"</span><span class="keyword">;<br />                throw new </span><span class="default">\Exception</span><span class="keyword">(</span><span class="string">"Bye"</span><span class="keyword">);<br />        }<br />} catch (</span><span class="default">\Exception $e</span><span class="keyword">) {<br />        echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" catch out\n"</span><span class="keyword">;<br />}<br /></span><span class="default">?&gt;<br /></span><br />The output is:<br /><br />Hello catch in<br />Hello finally <br />Bye catch out</span></code></div>
  </div>
 </div>
  <div class="note" id="122434">  <div class="votes">
    <div id="Vu122434">
    <a href="https://www.php.net/manual/vote-note.php?id=122434&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd122434">
    <a href="https://www.php.net/manual/vote-note.php?id=122434&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V122434" title="59% like this...">
    8
    </div>
  </div>
  <a href="language.exceptions.php.html#122434" class="name">
  <strong class="user"><em>mlaopane at gmail dot com</em></strong></a><a class="genanchor" href="language.exceptions.php.html#122434"> &para;</a><div class="date" title="2018-02-24 09:49"><strong>5 years ago</strong></div>
  <div class="text" id="Hcom122434">
<div class="phpcode"><code><span class="html"><span class="default">&lt;?php<br /><br /></span><span class="comment">/**<br /> * You can catch exceptions thrown in a deep level function<br /> */<br /><br /></span><span class="keyword">function </span><span class="default">employee</span><span class="keyword">()<br />{<br />    throw new </span><span class="default">\Exception</span><span class="keyword">(</span><span class="string">"I am just an employee !"</span><span class="keyword">);<br />}<br /><br />function </span><span class="default">manager</span><span class="keyword">()<br />{<br />    </span><span class="default">employee</span><span class="keyword">();<br />}<br /><br />function </span><span class="default">boss</span><span class="keyword">()<br />{<br />    try {<br />        </span><span class="default">manager</span><span class="keyword">();<br />    } catch (</span><span class="default">\Exception $e</span><span class="keyword">) {<br />        echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />    }<br />}<br /><br /></span><span class="default">boss</span><span class="keyword">(); </span><span class="comment">// output: "I am just an employee !"</span></span></code></div>
  </div>
 </div>
  <div class="note" id="117029">  <div class="votes">
    <div id="Vu117029">
    <a href="https://www.php.net/manual/vote-note.php?id=117029&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd117029">
    <a href="https://www.php.net/manual/vote-note.php?id=117029&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V117029" title="58% like this...">
    11
    </div>
  </div>
  <a href="language.exceptions.php.html#117029" class="name">
  <strong class="user"><em>Simo</em></strong></a><a class="genanchor" href="language.exceptions.php.html#117029"> &para;</a><div class="date" title="2015-04-04 02:47"><strong>8 years ago</strong></div>
  <div class="text" id="Hcom117029">
<div class="phpcode"><code><span class="html">#3 is not a good example. inverse("0a") would not be caught since (bool) "0a" returns true, yet 1/"0a" casts the string to integer zero and attempts to perform the calculation.</span></code></div>
  </div>
 </div>
  <div class="note" id="115240">  <div class="votes">
    <div id="Vu115240">
    <a href="https://www.php.net/manual/vote-note.php?id=115240&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd115240">
    <a href="https://www.php.net/manual/vote-note.php?id=115240&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V115240" title="56% like this...">
    9
    </div>
  </div>
  <a href="language.exceptions.php.html#115240" class="name">
  <strong class="user"><em>telefoontoestel at nospam dot org</em></strong></a><a class="genanchor" href="language.exceptions.php.html#115240"> &para;</a><div class="date" title="2014-06-18 12:34"><strong>9 years ago</strong></div>
  <div class="text" id="Hcom115240">
<div class="phpcode"><code><span class="html">When using finally keep in mind that when a exit/die statement is used in the catch block it will NOT go through the finally block. <br /><br /><span class="default">&lt;?php<br /></span><span class="keyword">try {<br />    echo </span><span class="string">"try block&lt;br /&gt;"</span><span class="keyword">;<br />    throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"test"</span><span class="keyword">);<br />} catch (</span><span class="default">Exception $ex</span><span class="keyword">) {<br />    echo </span><span class="string">"catch block&lt;br /&gt;"</span><span class="keyword">;<br />} finally {<br />    echo </span><span class="string">"finally block&lt;br /&gt;"</span><span class="keyword">;<br />}<br /><br /></span><span class="comment">// try block<br />// catch block<br />// finally block<br /></span><span class="default">?&gt;<br /></span><br /><span class="default">&lt;?php<br /></span><span class="keyword">try {<br />    echo </span><span class="string">"try block&lt;br /&gt;"</span><span class="keyword">;<br />    throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"test"</span><span class="keyword">);<br />} catch (</span><span class="default">Exception $ex</span><span class="keyword">) {<br />    echo </span><span class="string">"catch block&lt;br /&gt;"</span><span class="keyword">;<br />    exit(</span><span class="default">1</span><span class="keyword">);<br />} finally {<br />    echo </span><span class="string">"finally block&lt;br /&gt;"</span><span class="keyword">;<br />}<br /><br /></span><span class="comment">// try block<br />// catch block<br /></span><span class="default">?&gt;</span></span></code></div>
  </div>
 </div>
  <div class="note" id="116273">  <div class="votes">
    <div id="Vu116273">
    <a href="https://www.php.net/manual/vote-note.php?id=116273&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd116273">
    <a href="https://www.php.net/manual/vote-note.php?id=116273&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V116273" title="54% like this...">
    6
    </div>
  </div>
  <a href="language.exceptions.php.html#116273" class="name">
  <strong class="user"><em>Tom Polomsk</em></strong></a><a class="genanchor" href="language.exceptions.php.html#116273"> &para;</a><div class="date" title="2014-12-04 01:45"><strong>9 years ago</strong></div>
  <div class="text" id="Hcom116273">
<div class="phpcode"><code><span class="html">Contrary to the documentation it is possible in PHP 5.5 and higher use only try-finally blocks without any catch block.</span></code></div>
  </div>
 </div>
  <div class="note" id="106696">  <div class="votes">
    <div id="Vu106696">
    <a href="https://www.php.net/manual/vote-note.php?id=106696&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd106696">
    <a href="https://www.php.net/manual/vote-note.php?id=106696&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V106696" title="53% like this...">
    6
    </div>
  </div>
  <a href="language.exceptions.php.html#106696" class="name">
  <strong class="user"><em>Sawsan</em></strong></a><a class="genanchor" href="language.exceptions.php.html#106696"> &para;</a><div class="date" title="2011-11-28 09:36"><strong>12 years ago</strong></div>
  <div class="text" id="Hcom106696">
<div class="phpcode"><code><span class="html">the following is an example of a re-thrown exception and the using of getPrevious function:<br /><br /><span class="default">&lt;?php<br /><br />$name </span><span class="keyword">= </span><span class="string">"Name"</span><span class="keyword">;<br /><br /></span><span class="comment">//check if the name contains only letters, and does not contain the word name<br /><br /></span><span class="keyword">try<br />   {<br />   try<br />     {<br />      if (</span><span class="default">preg_match</span><span class="keyword">(</span><span class="string">'/[^a-z]/i'</span><span class="keyword">, </span><span class="default">$name</span><span class="keyword">)) <br />       {<br />           throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"</span><span class="default">$name</span><span class="string"> contains character other than a-z A-Z"</span><span class="keyword">);<br />       }   <br />       if(</span><span class="default">strpos</span><span class="keyword">(</span><span class="default">strtolower</span><span class="keyword">(</span><span class="default">$name</span><span class="keyword">), </span><span class="string">'name'</span><span class="keyword">) !== </span><span class="default">FALSE</span><span class="keyword">)<br />       {<br />          throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"</span><span class="default">$name</span><span class="string"> contains the word name"</span><span class="keyword">);<br />       }<br />       echo </span><span class="string">"The Name is valid"</span><span class="keyword">;<br />     }<br />   catch(</span><span class="default">Exception $e</span><span class="keyword">)<br />     {<br />     throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"insert name again"</span><span class="keyword">,</span><span class="default">0</span><span class="keyword">,</span><span class="default">$e</span><span class="keyword">);<br />     }<br />   }<br /> <br />catch (</span><span class="default">Exception $e</span><span class="keyword">)<br />   {<br />   if (</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">())<br />   {<br />    echo </span><span class="string">"The Previous Exception is: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">"&lt;br/&gt;"</span><span class="keyword">;<br />   }<br />   echo </span><span class="string">"The Exception is: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">"&lt;br/&gt;"</span><span class="keyword">;<br />   }<br /><br /> </span><span class="default">?&gt;</span></span></code></div>
  </div>
 </div>
  <div class="note" id="129177">  <div class="votes">
    <div id="Vu129177">
    <a href="https://www.php.net/manual/vote-note.php?id=129177&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd129177">
    <a href="https://www.php.net/manual/vote-note.php?id=129177&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V129177" title="100% like this...">
    1
    </div>
  </div>
  <a href="language.exceptions.php.html#129177" class="name">
  <strong class="user"><em>jlherren</em></strong></a><a class="genanchor" href="language.exceptions.php.html#129177"> &para;</a><div class="date" title="2024-01-19 08:24"><strong>25 days ago</strong></div>
  <div class="text" id="Hcom129177">
<div class="phpcode"><code><span class="html">As noted elsewhere, throwing an exception from the `finally` block will replace a previously thrown exception. But the original exception is magically available from the new exception's `getPrevious()`.<br /><br /><span class="default">&lt;?php<br /></span><span class="keyword">try {<br />    try {<br />        throw new </span><span class="default">RuntimeException</span><span class="keyword">(</span><span class="string">'Exception A'</span><span class="keyword">);<br />    } finally {<br />        throw new </span><span class="default">RuntimeException</span><span class="keyword">(</span><span class="string">'Exception B'</span><span class="keyword">);<br />    }<br />}<br />catch (</span><span class="default">Throwable $exception</span><span class="keyword">) {<br />    echo </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">(), </span><span class="string">"\n"</span><span class="keyword">;<br />    </span><span class="comment">// 'previous' is magically available!<br />    </span><span class="keyword">echo </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">(), </span><span class="string">"\n"</span><span class="keyword">;<br />}<br /></span><span class="default">?&gt;<br /></span><br />Will print:<br /><br />Exception B<br />Exception A</span></code></div>
  </div>
 </div>
  <div class="note" id="128119">  <div class="votes">
    <div id="Vu128119">
    <a href="https://www.php.net/manual/vote-note.php?id=128119&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd128119">
    <a href="https://www.php.net/manual/vote-note.php?id=128119&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V128119" title="44% like this...">
    -1
    </div>
  </div>
  <a href="language.exceptions.php.html#128119" class="name">
  <strong class="user"><em>lscorionjs at gmail dot com</em></strong></a><a class="genanchor" href="language.exceptions.php.html#128119"> &para;</a><div class="date" title="2023-01-16 04:03"><strong>1 year ago</strong></div>
  <div class="text" id="Hcom128119">
<div class="phpcode"><code><span class="html"><span class="default">&lt;?php<br /><br /></span><span class="keyword">try {<br />  </span><span class="default">$str </span><span class="keyword">= </span><span class="string">'hi'</span><span class="keyword">;<br />  throw new </span><span class="default">Exception</span><span class="keyword">();<br />} catch (</span><span class="default">Exception</span><span class="keyword">) {<br />  </span><span class="default">var_dump</span><span class="keyword">(</span><span class="default">$str</span><span class="keyword">);<br />} finally {<br />  </span><span class="default">var_dump</span><span class="keyword">(</span><span class="default">$str</span><span class="keyword">);<br />}<br /><br /></span><span class="default">?&gt;<br /></span><br />Output:<br />string(2) "hi"<br />string(2) "hi"</span></code></div>
  </div>
 </div>
  <div class="note" id="128041">  <div class="votes">
    <div id="Vu128041">
    <a href="https://www.php.net/manual/vote-note.php?id=128041&amp;page=language.exceptions&amp;vote=up" title="Vote up!" class="usernotes-voteu">up</a>
    </div>
    <div id="Vd128041">
    <a href="https://www.php.net/manual/vote-note.php?id=128041&amp;page=language.exceptions&amp;vote=down" title="Vote down!" class="usernotes-voted">down</a>
    </div>
    <div class="tally" id="V128041" title="33% like this...">
    -2
    </div>
  </div>
  <a href="language.exceptions.php.html#128041" class="name">
  <strong class="user"><em>ilia-yats at ukr dot net</em></strong></a><a class="genanchor" href="language.exceptions.php.html#128041"> &para;</a><div class="date" title="2022-12-23 12:24"><strong>1 year ago</strong></div>
  <div class="text" id="Hcom128041">
<div class="phpcode"><code><span class="html">Note some undocumented details about exceptions thrown from 'finally' blocks. <br /><br />When exception is thrown from 'finally' block, it overrides the original not-caught (or re-thrown) exception. So the behavior is similar to 'return': value returned from 'finally' overrides the one returned earlier. And the original exception is automatically appended to the exceptions chain, i.e. becomes 'previous' for the new one. Example:<br /><span class="default">&lt;?php<br /></span><span class="keyword">try {<br />    try {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'thrown from try'</span><span class="keyword">);<br />    } finally {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'thrown from finally'</span><span class="keyword">);<br />    }<br />} catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />    echo </span><span class="default">PHP_EOL</span><span class="keyword">;<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />} <br /><br /></span><span class="comment">// will output:<br />// thrown from finally<br />// thrown from try<br /></span><span class="default">?&gt;<br /></span><br />Example with re-throwing:<br /><span class="default">&lt;?php<br /></span><span class="keyword">try {<br />    try {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'thrown from try'</span><span class="keyword">);<br />    } catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'thrown from catch'</span><span class="keyword">);<br />    } finally {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'thrown from finally'</span><span class="keyword">);<br />    }<br />} catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />    echo </span><span class="default">PHP_EOL</span><span class="keyword">;<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />} <br /><br /></span><span class="comment">// will output:<br />// thrown from finally<br />// thrown from catch<br /></span><span class="default">?&gt;<br /></span><br />The same happens even if explicitly pass null as previous exception:<br /><span class="default">&lt;?php<br /></span><span class="keyword">try {<br />    try {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'thrown from try'</span><span class="keyword">);<br />    } finally {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'thrown from finally'</span><span class="keyword">, </span><span class="default">null</span><span class="keyword">, </span><span class="default">null</span><span class="keyword">);<br />    }<br />} catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />    echo </span><span class="default">PHP_EOL</span><span class="keyword">;<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />} <br /><br /></span><span class="comment">// will output:<br />// thrown from finally<br />// thrown from try<br /></span><span class="default">?&gt;<br /></span><br />Also it is possible to pass previous exception explicitly, the 'original' one will be still appended to the chain, e.g.:<br /><span class="default">&lt;?php<br /></span><span class="keyword">try {<br />    try {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'thrown from try'</span><span class="keyword">);<br />    } finally {<br />        throw new </span><span class="default">Exception</span><span class="keyword">(<br />            </span><span class="string">'thrown from finally'</span><span class="keyword">,<br />            </span><span class="default">null</span><span class="keyword">, <br />            new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'Explicitly set previous!'</span><span class="keyword">)<br />        );<br />    }<br />} catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />    echo </span><span class="default">PHP_EOL</span><span class="keyword">;<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />    echo </span><span class="default">PHP_EOL</span><span class="keyword">;<br />    echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />} <br /><br /></span><span class="comment">// will output:<br />// thrown from finally<br />// Explicitly set previous!<br />// thrown from try<br /></span><span class="default">?&gt;<br /></span><br />This seems to be true for versions 5.6-8.2.</span></code></div>
  </div>
 </div></div>
<div class="foot"><a href="https://www.php.net/manual/add-note.php?sect=language.exceptions&amp;redirect=https://www.php.net/manual/ru/language.exceptions.php">＋<small>add a note</small></a></div>
</section>    </section><!-- layout-content -->
        <aside class='layout-menu'>

        <ul class='parent-menu-list'>
                                    <li>
                <a href="langref.php.html">Справочник языка</a>

                                    <ul class='child-menu-list'>

                                                <li class="">
                            <a href="language.basic-syntax.php.html" title="Основы синтаксиса">Основы синтаксиса</a>
                        </li>
                                                <li class="">
                            <a href="language.types.php.html" title="Типы">Типы</a>
                        </li>
                                                <li class="">
                            <a href="language.variables.php.html" title="Переменные">Переменные</a>
                        </li>
                                                <li class="">
                            <a href="language.constants.php.html" title="Константы">Константы</a>
                        </li>
                                                <li class="">
                            <a href="language.expressions.php.html" title="Выражения">Выражения</a>
                        </li>
                                                <li class="">
                            <a href="language.operators.php.html" title="Операторы">Операторы</a>
                        </li>
                                                <li class="">
                            <a href="language.control-structures.php.html" title="Управляющие конструкции">Управляющие конструкции</a>
                        </li>
                                                <li class="">
                            <a href="language.functions.php.html" title="Функции">Функции</a>
                        </li>
                                                <li class="">
                            <a href="language.oop5.php.html" title="Классы и объекты">Классы и объекты</a>
                        </li>
                                                <li class="">
                            <a href="language.namespaces.php.html" title="Пространства имён">Пространства имён</a>
                        </li>
                                                <li class="">
                            <a href="language.enumerations.php.html" title="Перечисления">Перечисления</a>
                        </li>
                                                <li class="">
                            <a href="language.errors.php.html" title="Ошибки">Ошибки</a>
                        </li>
                                                <li class="current">
                            <a href="language.exceptions.php.html" title="Исключения">Исключения</a>
                        </li>
                                                <li class="">
                            <a href="language.fibers.php.html" title="Fibers">Fibers</a>
                        </li>
                                                <li class="">
                            <a href="language.generators.php.html" title="Генераторы">Генераторы</a>
                        </li>
                                                <li class="">
                            <a href="language.attributes.php.html" title="Атрибуты">Атрибуты</a>
                        </li>
                                                <li class="">
                            <a href="language.references.php.html" title="Объяснение ссылок">Объяснение ссылок</a>
                        </li>
                                                <li class="">
                            <a href="reserved.variables.php.html" title="Предопределённые переменные">Предопределённые переменные</a>
                        </li>
                                                <li class="">
                            <a href="reserved.exceptions.php.html" title="Предопределённые исключения">Предопределённые исключения</a>
                        </li>
                                                <li class="">
                            <a href="reserved.interfaces.php.html" title="Встроенные интерфейсы и классы">Встроенные интерфейсы и классы</a>
                        </li>
                                                <li class="">
                            <a href="reserved.attributes.php.html" title="Предопределённые атрибуты">Предопределённые атрибуты</a>
                        </li>
                                                <li class="">
                            <a href="context.php.html" title="Контекстные опции и параметры">Контекстные опции и параметры</a>
                        </li>
                                                <li class="">
                            <a href="wrappers.php.html" title="Поддерживаемые протоколы и обёртки">Поддерживаемые протоколы и обёртки</a>
                        </li>
                        
                    </ul>
                
            </li>
                        
                    </ul>
    </aside>


  </div><!-- layout -->

  <footer>
    <div class="container footer-content">
      <div class="row-fluid">
      <ul class="footmenu">
        <li><a href="https://www.php.net/copyright.php">Copyright &copy; 2001-2024 The PHP Group</a></li>
        <li><a href="https://www.php.net/my.php">My PHP.net</a></li>
        <li><a href="https://www.php.net/contact.php">Contact</a></li>
        <li><a href="https://www.php.net/sites.php">Other PHP.net sites</a></li>
        <li><a href="https://www.php.net/privacy.php">Privacy policy</a></li>
      </ul>
      </div>
    </div>
  </footer>

    
 <!-- External and third party libraries. -->
 <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="../../cached.php%3Ft=1657730402&amp;f=%252Fjs%252Fext%252Fhogan-3.0.2.min.js"></script>
<script src="../../cached.php%3Ft=1421837618&amp;f=%252Fjs%252Fext%252Ftypeahead.min.js"></script>
<script src="../../cached.php%3Ft=1657876202&amp;f=%252Fjs%252Fext%252Fmousetrap.min.js"></script>
<script src="../../cached.php%3Ft=1657730402&amp;f=%252Fjs%252Fext%252Fjquery.scrollTo.min.js"></script>
<script src="../../cached.php%3Ft=1701958202&amp;f=%252Fjs%252Fsearch.js"></script>
<script src="../../cached.php%3Ft=1701958202&amp;f=%252Fjs%252Fcommon.js"></script>

<a id="toTop" href="javascript:;"><span id="toTopHover"></span><img width="40" height="40" alt="To Top" src="../../images/to-top@2x.png"></a>

</body>
</html>
